In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Load the data
df = pd.read_csv("heart.csv")
df.sample(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
783,45,F,ASY,138,236,0,LVH,152,Y,0.2,Flat,0
832,51,M,NAP,94,227,0,Normal,154,Y,0.0,Up,0
180,52,M,ASY,130,225,0,Normal,120,Y,2.0,Flat,1
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1
477,61,M,ASY,110,0,1,Normal,108,Y,2.0,Down,1